export const CLEAR_ALERT = 'CLEAR_ALERT';
export const DISPLAY_ALERT = 'DISPLAY_ALERT';
export const HANDLE_CHANGE = 'HANDLE_CHANGE';

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN';
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR';
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS';

